Repository VenusProtocol/venus-protocol, pull requests merged in 2024-03, with the labels that each got.

#417 [VEN-2262]: Functionality for seizing xvs tokens
  contracts/Comptroller/Diamond/facets/RewardFacet.sol
  contracts/Comptroller/Diamond/interfaces/IRewardFacet.sol
  tests/hardhat/Comptroller/Diamond/accessControl.ts
  tests/hardhat/Fork/claimRewards.ts
Labels: don't merge, audit

#414 [VEN -2250] Reduce reserves with available cash
  contracts/Tokens/VTokens/VToken.sol
  hardhat.config.ts
  package.json
  tests/Tokens/reservesTest.js
  tests/hardhat/Comptroller/Diamond/accessControl.ts
  tests/hardhat/Comptroller/Diamond/assetListTest.ts
  tests/hardhat/Comptroller/Diamond/comptrollerTest.ts
  tests/hardhat/Fork/swapTest.ts
  tests/hardhat/VToken/reservesTest.ts
  tests/hardhat/fixtures/ComptrollerWithMarkets.ts
  yarn.lock
Labels: audit

#456 [VEN-2433] : VTreasuryV8 deployment on Arbitrum Sepolia
  .env.example
  .github/workflows/ci.yml
  deploy/005-deploy-VTreasuryV8.ts
  deployments/arbitrumone.json
  deployments/arbitrumone_addresses.json
  deployments/arbitrumsepolia.json
  deployments/arbitrumsepolia/.chainId
  deployments/arbitrumsepolia/VTreasuryV8.json
  deployments/arbitrumsepolia/solcInputs/d925487db1962eca6f5f2036a8e29be8.json
  deployments/arbitrumsepolia_addresses.json
  hardhat.config.ts
Labels: arbitrum sepolia
